# .github/workflows/render-keep-alive.yml
name: Keep TacoDog Alive

on:
  schedule:
    - cron: '*/1 0-10 * * *' # Runs every 5 minutes from 8AM–6PM GMT+8 (0–10 UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping TacoDog app
        run: curl -s https://tacodog.onrender.com
